### ISSUE TITLE
Arc Reactor does not really work (Update 4)

### ISSUE THREAD

**Issue by MozeOfficial** [mrhid6/SF_Mod_RefinedPower#111]
I`ve built the arc reactor, but the problem is that it doesnt output any Energy. If im true i´ve double checked, if it has everything it needs (coolant and cores) and yeah as said it doesnt work. The game is on Update 4.

**Comment by Imachicken29** [comment]
the arc reactor works, it is just not producing more than needed like the old power system worked before update 4. this will change due to it not charging batteries with how the ingame power system worked which is why CSS had to change from, "consuming and producing the exact amount needed" to always producing as much as possible and consuming as much as possible

**Comment by MozeOfficial** [comment]
Oh Ok thx for your help :D
