### ISSUE TITLE
Coal generators not providing stated power outputs

### ISSUE THREAD

**Issue by Diantane** [mrhid6/SF_Mod_RefinedPower#263]
The reason I tried going to a Mk2 turbine was because of this other issue:

Coal heater, Mk1 turbine, Mk1 or Mk2 boiler
LV states 175mw (actual 150)
MV states 300mw (actual 182)
HV states 500mw (actual 176)

There's no difference between using a Mk1 and Mk2 boiler

**Comment by Kyri123** [comment]
Please read the docs that I posted last issue report.

here is the direct link to Turbines and Generators!
https://docs.ficsit.app/refinedrd/latest/rp/buildings/modularpower/MP-Turbines.html
https://docs.ficsit.app/refinedrd/latest/rp/buildings/modularpower/MP-Generators.html

LV states 150mw at 10,000 RPM (the description is wrong here will be fixed in 3.1.1)
MV states 300mw at 17,000 RPM
HV states 500mw at 25,000 RPM 

Mk Turbine has a max of 10,000 RPM 
Mk2 Turbine has a maximum of 25,000 RPM

**Comment by Diantane** [comment]
Thanks for the info. Made notes of all. Too bad this info is not on the ingame description.
